### ISSUE TITLE
Links in CONTRIBUTING.md are broken

### ISSUE THREAD

**Issue by D0han** [ProteGO-Safe/web#1]
**Describe the bug**
Links in https://github.com/ProteGO-Safe/web/blob/master/.github/CONTRIBUTING.md are broken

**To Reproduce**
Click on link to License.

**Expected behavior**
Redirection to file describing License

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by bartosztomczak** [comment]
Thanks, it's been fixed.
