### ISSUE TITLE
Zależność od fonts.googleapis.com

### ISSUE THREAD

**Issue by jasisz** [ProteGO-Safe/web#10]
Aplikacja używa zewnętrzenego serwisu https://fonts.googleapis.com do ściągnięcia czcionek, które powinny być zawarte lokalnie.

**Comment by Tarvald** [comment]
@jasisz 
Zgłoszenie zostało przyjęte
Wewnętrzny numer zgłoszenia to: PSAFE-825

**Comment by SeraMoon** [comment]
@Tarvald na jakim etapie jest to zgłoszenie? Gdzie mogę zapoznać się bez potrzeby logowania się z "PSAFE-825"?

**Comment by SeraMoon** [comment]
Ponawiam pytanie powyżej. @Tarvald

**Comment by thecodersio** [comment]
Wszystkie zależności zewnętrzne zostały usunięte w raz wejściem kompilowania aplikacji do wersji tzw. offline.

Zamykam temat.
