### ISSUE TITLE
Informacja o stosowaniu ciasteczek przez aplikację!

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/web#11]
**Describe the bug**
Po wejściu na safesafe.app nie widzę informacji o stosowaniu ciasteczek. Tymczasem aplikacja zapisuje ciasteczko w chwili zaczęcia wykonywania testu zdrowia:

```
{"Response cookies":{"__cfduid":{"domain":".safesafe.app","expires":"2020-06-04T23:32:32.000Z","httpOnly":true,"path":"/","samesite":"Lax","secure":true,"value":"d52c564ec4d3765b50ef757e20efd54cf1588721552"}}}
```

**To Reproduce**
1. Uruchomić wskazaną stronę
2. Włączyć tryb F12 i tab Network
3. Rozpocząć test zdrowia
4. sprawdzić żądania i odpowiedzi do zapytań "diagnosis"

**Expected behavior**
- [ ] Usunięcie ciasteczek lub wyraźny komunikat zarówno w aplikacji webowej jak i na smartfon, że stosowane będą ciasteczka i (jeżeli są) inne technologi typu pixele itp. itd. 
- [ ] Udokumentowanie do czego jest stosowane które ciasteczko, szczególnie "__cfduid". 

**Screenshots**
\-

**Desktop (please complete the following information):**
 - OS: Dowolny
 - Browser Firefox
 - Version 68 ESR

**Smartphone (please complete the following information):**
 - Device: \-
 - OS: Android, iOS
 - Browser \-
 - Version \-

**Additional context**
ProteGO-Safe/specs#157 ProteGO-Safe/specs#129

**Comment by pingwinwzakiecie** [comment]
@Tarvald Czy problem został już rozwiązany? Nie zajmuję się tą aplikacją, pytam z ciekawości.

**Comment by Tarvald** [comment]
@pingwinwzakiecie 
W trakcie realizacji.
Jest to cookie dodawane przez cloudflare.

https://support.cloudflare.com/hc/en-us/articles/200170156-Understanding-the-Cloudflare-Cookies

Informacja o użyciu cookie zostanie dodana.

**Comment by ravkr** [comment]
@Tarvald cloudflare w ogóle nie powinno być używane

**Comment by SeraMoon** [comment]
> Informacja o użyciu cookie zostanie dodana.
@Tarvald dlaczego wciąż nie wyświetla mi się ta informacja (np. na dole strony) do czasu jej zamknięcia)? Wiesz o tym, że zgodnie z prawem powinnam być poinformowana o tym przy pierwszym żądaniu do serwera z którego wróci czytelna dla człowieka odpowiedź (czytaj - pierwszy HTML)? 

Opcją jest umieszczenie na ekranie powitalnym linka do polityki ciasteczkowej.

**Comment by Tarvald** [comment]
Prawo webowe to nie moja specjalizacja.
Problem został zgłoszony

**Comment by SeraMoon** [comment]
> Problem został zgłoszony

Gdzie mogę obejrzeć zgłoszenie? Gdzie został zgłoszony?

**Comment by Tarvald** [comment]
@SeraMoon 
Informacja o ciasteczkach została dodana w regulaminie. Czy to wystarczy?

**Comment by SeraMoon** [comment]
Nie. Tak informacja powinna być dostępna od razu po wejściu na stronę.

**Comment by Marooned-MB** [comment]
Informacja w regulaminie jak najbardziej wystarczy. Wszelkie popupy o ciasteczkach to absolutna zakała Internetu i powinna zniknąć tak samo jak IE6.
