### ISSUE TITLE
Prywatność, IP i wysyłanie danych medycznych powiązanych z IP

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/web#16]
**Describe the bug**
Aplikacja (używałam safesafe.app) wysyła dane na serwer podczas gdy są to dane wrażliwe w rozumieniu RODO. Poniżej log z przypadkowego użycia aplikacji (dane nie są prawdziwe toteż mogą pozostać publicznie

```
diagnosis | {"sex":"female","age":35,"evidence":[]}
diagnosis | {"sex":"female","age":35,"evidence":[{"id":"p_16","choice_id":"absent"},{"id":"p_17","choice_id":"absent"},{"id":"p_18","choice_id":"absent"},{"id":"p_19","choice_id":"present"},{"id":"p_20","choice_id":"absent"},{"id":"p_21","choice_id":"absent"},{"id":"p_22","choice_id":"absent"}]}
diagnosis | {"sex":"female","age":35,"evidence":[{"id":"p_16","choice_id":"absent"},{"id":"p_17","choice_id":"absent"},{"id":"p_18","choice_id":"absent"},{"id":"p_19","choice_id":"present"},{"id":"p_20","choice_id":"absent"},{"id":"p_21","choice_id":"absent"},{"id":"p_22","choice_id":"absent"}]}
diagnosis | {"sex":"female","age":35,"evidence":[{"id":"p_16","choice_id":"absent"},{"id":"p_17","choice_id":"absent"},{"id":"p_18","choice_id":"absent"},{"id":"p_19","choice_id":"present"},{"id":"p_20","choice_id":"absent"},{"id":"p_21","choice_id":"absent"},{"id":"p_22","choice_id":"absent"}]}
diagnosis | {"sex":"female","age":35,"evidence":[{"id":"p_16","choice_id":"absent"},{"id":"p_17","choice_id":"absent"},{"id":"p_18","choice_id":"absent"},{"id":"p_19","choice_id":"present"},{"id":"p_20","choice_id":"absent"},{"id":"p_21","choice_id":"absent"},{"id":"p_22","choice_id":"absent"}]}
diagnosis | {"sex":"female","age":35,"evidence":[{"id":"p_16","choice_id":"absent"},{"id":"p_17","choice_id":"absent"},{"id":"p_18","choice_id":"absent"},{"id":"p_19","choice_id":"present"},{"id":"p_20","choice_id":"absent"},{"id":"p_21","choice_id":"absent"},{"id":"p_22","choice_id":"absent"}]}
diagnosis | {"sex":"female","age":35,"evidence":[{"id":"p_16","choice_id":"absent"},{"id":"p_17","choice_id":"absent"},{"id":"p_18","choice_id":"absent"},{"id":"p_19","choice_id":"present"},{"id":"p_20","choice_id":"absent"},{"id":"p_21","choice_id":"absent"},{"id":"p_22","choice_id":"absent"}]}
diagnosis | {"sex":"female","age":35,"evidence":[{"id":"p_16","choice_id":"absent"},{"id":"p_17","choice_id":"absent"},{"id":"p_18","choice_id":"absent"},{"id":"p_19","choice_id":"present"},{"id":"p_20","choice_id":"absent"},{"id":"p_21","choice_id":"absent"},{"id":"p_22","choice_id":"absent"}]}
Response:
{"description":"Twoje objawy s\u0105 bardzo powa\u017cne i mog\u0105 wskazywa\u0107 na zaka\u017cenie koronawirusem (choroba COVID-19).","label":"Zadzwo\u0144 pod numer alarmowy. Unikaj kontaktu z innymi osobami.","serious":[{"common_name":"Kaszel","id":"s_1","is_emergency":false,"name":"Kaszel"},{"common_name":"Gor\u0105czka poni\u017cej 40\u00b0C","id":"s_3","is_emergency":false,"name":"Gor\u0105czka poni\u017cej 40\u00b0C"},{"common_name":"Szybkie pogarszanie stanu zdrowia","id":"s_12","is_emergency":true,"name":"Szybkie pogarszanie stanu zdrowia"},{"common_name":"Odkrztuszanie krwi","id":"s_14","is_emergency":true,"name":"Odkrztuszanie krwi"}],"triage_level":"isolation_ambulance"}
```
\<SARS>

**To Reproduce**
- Uruchom aplikację safesafe.app
- Włącz w przeglądarce tryb F12
- Przełącz na Network
- wypełnij pierwszy raz formatkę dotyczącą oceny ryzyka i podejrzyj wysłane dane oraz uzyskane odpowiedzi dla wpisów "diagnosis". 

Zobacz wyżej. 

**Expected behavior**
Wszystko powinno zostać wykonane w JavaScripcie i w local storage / ciasteczku zapisany wynik "oceny ryzyka". Liczone powinno być lokalnie na komputerze / smartfonie. 

**Screenshots**
Nie przewidziano - jest załączony log powyżej. 

**Desktop (please complete the following information):**
Nieistotne, dowolny

**Smartphone (please complete the following information):**
Nieistotne, dowolny

**Additional context**
Aplikacja łamie prawo do prywatności, ponieważ nie komunikuje się przez Tora - dzięki "Ustawie inwigilacyjnej" możliwa jest deanonimizacja człowieka który zaznaczył te odpowiedzi i które dotarły na serwer. Możliwy jest podgląd przez służby specjalne historii wypełnianych testów. 

Do sprawdzenia: czy nie dzieje się tak przy użyciu innych elementów aplikacji - np. wypełniania dziennika. 

Przepraszam za sto dwudziestą siódmą zasmarkaną chusteczkę ale aplikacja ma w poważaniu prywatność użytkownika. 

Możliwe rozwiązania - przechowywanie zaszyfrowanej mocnym hasłem historii chorób / dolegliwości użytkownika - szyfrowanie mocne, minimum 256 bitowe - wymaganie od użytkownika mocnego hasła, które może przechowywać lokalnie, np. w przeglądarce lub dla aplikacji natywnych - w pliku. Dane są dla zapewnienia prywatności (czy użytkownik w ogóle korzysta z protego) - przesyłane przez sieć Tor. 

**Tak wygląda prawdziwa prywatność**, a nie atrapa prywatności. 

\<SARS> \<SARS> Proszę o maski z drucikiem u góry, bo spojówki już mnie bolą o te nieszczelności.

**Comment by Tarvald** [comment]
@SeraMoon 
Wątek ponowanie otwarty i przeniosiony do web. 
Prośba o nieoftopowanie w innych wątkach. 
Czytam wszystkie update na GH.

**Comment by SeraMoon** [comment]
@Tarvald dziękuję za re-open (ponowne otwarcie) wątku - bowiem **prawdopodobnie** dotyczy teraz już tylko wersji web (inne platformy do sprawdzenia - nie mam możliwości przetestowania wersji na Androida i iOS). Jednak zauważę:

> @SeraMoon
Nie mineły nawet 24h od twojej prośoby o ponowanie otwarcie i przeniesie wątku do /web.
Prośba o zaprzestanie ciągłego offtopowania.
Wątek #127 został otwarty i przeniesiony.
> 
> ps. zamknięcie wątku to miss click w aplikacji PWA GH. Klient natywny nadal nie oferuje pełnych funkcji.

Tymczasem: 

>  Tarvald commented 19 hours ago
> Samoocena ryzyka zarażenia COVID-19 została zaimplementowana lokalnie w ver 4.1.1
>
> Tarvald closed this 19 hours ago

Wygląda nie na misclick (nieprawidłowe kliknięcie), ale na niezauważenie, że temat dotyczył kilku platfom (misclicki faktycznie widoczne w wielu innych tematach, zakończone ponownym otwarciem po kilku minutach). 

Wersja przeglądarkowa działa dobrze i wygląda na to, że są dostępne wszystkie potrzebne funkcje - przynajmniej ja widzę je w swoim biednym "repozytorium". Może to rozwiąże ten częsty problem z misclickiem.

**Comment by pkleczko** [comment]
Aplikacja webowa została wyłączona, moduł ten w aplikacjach mobilnych nie komunikuje się z żadnym serwerem, więc temat można zamknąć.
