### ISSUE TITLE
Pytanie o imię nie spełnia założeń dotyczących anonimowości

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/web#17]
**Describe the bug**
Aplikacja pyta o imię i płeć, które mogą identyfikować użytkownika. Mniejszości seksualne (szczególnie osoby transseksualne) mogą tu odczuć spory dyskomfort psychiczny zamiast "komfortu użytkownika". 

**To Reproduce**
1. Po prostu uruchom aplikację i przejdź pierwsze kilka ekranów. 

**Expected behavior**
- [ ] Brak pytania o imię lub wyraźne pytanie o "nazwę użytkownika" - pytanie to godzi w anonimowość, ponadto jest daną identyfikującą. [Zapisano](https://archive.fo/UFmX4#selection-2089.168-2089.298), że aplikacja nie pyta o takie dane a pyta jedynie o dowolną nazwę dla komfortu użytkownika (wątpliwego - Thunderbird, Firefox, Tor Browser, Nautilus i inne programy nie pytają mnie o imię i nie mam z tym problemu). Jakiej odpowiedzi ma udzielić ponadto osoba transseksualna, gdy ma postawione pytanie "jak masz na imię?". Ma podać to z dowodu osobistego? Pytanie brzmi jak masz na imię, nie zaś, jak chcesz mieć na imię... 

- [ ] Brak pytania o płeć - może godzić wprost w dobra osobiste osób transseksualnych. 

[EDIT]
Po zgłębieniu tematu (jako, że wiem, że część krajów umożliwia zaznaczenie płci "innej") - co ma zaznaczyć osoba z [Syndromem Swyera](https://pl.wikipedia.org/wiki/Zesp%C3%B3%C5%82_Swyera), skoro ma cechy płci męskiej i żeńskiej jednocześnie (zaś po urodzeniu wpisując do dokumentu - rzucano kostką do gry)? 

Co ma zaznaczyć [Semenya Caster](https://en.wikipedia.org/wiki/Caster_Semenya) - ma wysoki poziom testosteronu, genotyp XY i jednocześnie nie jest zbudowana ani jak kobieta ani jak mężczyzna? 

@Dr-Kownacki, jaki procent w Polsce mamy tego typu osób transseksualnych i interseksualnych łącznie, gdzie coś się "nie udało" w zakresie płci? Pytam na wypadek, gdyby miało to znaczenie dla rokowania ryzyk związanych z COVID-19 (stawiam na wysokie ryzyko ze względu na wadliwe geny i współistniejące problemy anatomiczno-metaboliczne). 

Aplikacja zdaje się blokować im dostęp do merytorycznej dalszej oceny stanu zdrowia - innej niż korzystanie z EN (Exposure Notification od Google) -  bowiem niezaznaczenie pola kobieta/mężczyzna i niemożliwość zaznaczenia obu na raz - powoduje, że nie da się przejść dalej - szary przycisk. 

**Screenshots**
![screenshoot](https://i.ibb.co/SnzFGms/safe.jpg)

**Desktop (please complete the following information):**
 - OS: None
 - Browser Any
 - Version Unknown.

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: None
 - Browser None
 - Version 4.1.1

**Additional context**
[#203 (specs)](https://github.com/ProteGO-Safe/specs/issues/203)

----

W zwiqązku z tym, że prezydent Polski Andrzej Duda nazywa osoby LGBT ideologią - wszystkie zgłoszenia będą analizowane w obronie i potraktowaniu na poważnie problemów medycznych rozpatrywane też z perspektywy tego typu osób. (LGBT to nie ideologia, ale wrodzony problem medyczny [T] co wykazało wiele przeprowadzonych badań w tym anatomicznych lub problem z nieakceptacji różnorodności [LGB]). Aplikacja musi być przyjazna również osobom LGBT. 

BTW. Nie jest to wtręt polityczny z uwagi na **oficjalny** charakter wypowiedzi prezydenta Polski i zagrożenia jakie powodują tego typu słowa, a aplikacja ma być dla wszystkich i dla wszystkich ma być miła w obsłudze.

**Comment by Tarvald** [comment]
Tutaj zostało powiedziane że kolejne update przyniosą zmiany w pytaniach o płeć
https://github.com/ProteGO-Safe/specs/issues/201#issuecomment-646559936

**Comment by pkleczko** [comment]
@SeraMoon czy możemy zamknąć zgłoszenie? Aplikacja nie pyta już więcej o imię tylko o nick, jest on też dobrowolny
