### ISSUE TITLE
Wybór płci i forma gramatyczna

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/web#2]
Skoro aplikacja pyta o płeć Kobieta / Mężczyzna, to powinna stosować odpowiednią formę gramatyczną. 

Tymczasem w Kim jesteś wybrałam Kobieta, w następnym pytaniu:

> Czy cierpisz na jakąś dolegliwość?
> Nie, jestem **zdrowy** i nie cierpię na przewlekłe choroby
> Tak, jestem przewlekle **chory**
> Zaznacz dolegliwość, na którą cierpisz:
>nadciśnienie tętnicze
> przewlekłe choroby układu oddechowego
> choroby układu krążenia - choroba niedokrwienna serca [...]

Są 3 opcje:
- zastosować "chora/y",
- zastosować np. znak \xFE i za pomocą str_replace lub split().join() zmienić zależnie od płci na "a" lub "y",
- przeredagować tak aby nie było słów określających płeć, (na prawdę się da!) np. 

> Czy cierpisz na jakąś dolegliwość?
> **Nie narzekam na zdrowie** i nie cierpię na przewlekłe choroby
> Tak,, **choruję przewlekle**: 
> Zaznacz dolegliwość, na którą cierpisz:
>nadciśnienie tętnicze
> przewlekłe choroby układu oddechowego
> choroby układu krążenia - choroba niedokrwienna serca [...]

---

Przepraszam za zasmarkaną drugą chusteczkę 😸 

BTW. zmieńcie wszędzie "koronawirusem"  na "koronawirusem SARS-CoV-2". 229E oraz NL63 to też koronawirusy którymi można się zarazić. 

Pytając o gorączkę - podajcie jakie jest minimum, czy polskie >38.0°C, czy chińskie >37.5°C, czy też stan podgorączkowy >37.0°C. Nie każdy jest medykiem a kryterium gorączki zależnie od klasyfikacji bywa różne. Miejsce pomiaru?

Przenoszę zgłoszenie zgodnie z prośbą qLb.

**Comment by qLb** [comment]
closed in favor of #3 with full comments
