### ISSUE TITLE
Broken links in repo meta files

### ISSUE THREAD

**Issue by piotr-cz** [ProteGO-Safe/web#27]
**Describe the bug**

Broken links in following pages:

- [/.github/CONTRIBUTING.md](../blob/4.2.4/.github/CONTRIBUTING.md)
- [/CONTRIBUTORS.md](../blob/4.2.4/CONTRIBUTORS.md)

**To Reproduce**
1. Go to one of listed files
2. Click on link
4. See GitHub 404 error

**Expected behavior**
Links should work as expected

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version not specified

**Smartphone (please complete the following information):**
none

**Additional context**
none

**Comment by qLb** [comment]
Dziekuje serdecznie za wskazanie tego bledu.
Odpowiednia poprawka dotarla juz dzis w wersji 4.3.0

**Comment by piotr-cz** [comment]
- [x] `/.github/CONTRIBUTING.md` fixed in da9f15f595cf3981a0f71e91cb713ba1b91b8030
- [ ] `/CONTRIBUTORS.md`

**Comment by qLb** [comment]
Przepraszamy za opoznienie - problem zostal rozwiazany w #34.
