### ISSUE TITLE
Start script broken on Windows

### ISSUE THREAD

**Issue by piotr-cz** [ProteGO-Safe/web#28]
**Describe the bug**
The `start` script is broken on Windows OS

**To Reproduce**
1. Use dev machine with Windows OS
2. Run `yarn start`/ `npm start`
```
yarn run v1.22.5
$ PORT=3001 react-scripts start
'PORT' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
Development server starts at port 3001

**Screenshots**
none provided

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
`PORT` is one of the environment variables defined in [CRA/ Advanced configuration](https://create-react-app.dev/docs/advanced-configuration/).

To define environment variable on Windows OS, une must use `set` command, ie `set PORT=3001` as described [here](https://create-react-app.dev/docs/using-https-in-development/).

Usually I'd recommend using tool such as [cross-env](https://www.npmjs.com/package/cross-env), however as PORT may (and by default is recommended to) be set in the `.env` file I think it's better to move it to `.env.dist` file:

```ini
# See https://create-react-app.dev/docs/advanced-configuration/
# Start development server on port 3001
PORT=3001
```

This may be considered minor breaking change as dev server will start at default port `3000` unless developer will update one of the local `.env*` files.

In my opinion this is a minor issue as by default dev server is set up to automatically open new browser with proper URL anyway.

**Workaround**
```sh
node_modules\.bin\react-scripts start
```

**Comment by qLb** [comment]
I'm sorry but we supprt UNIX based developer environments. Why don't You try WSL?

**Comment by piotr-cz** [comment]
Windows is perfectly fine for development for me (especially web apps), for more complex projects I use VMs.

I guess your reason to pick up other port than default (3000) is that you may develop different projects in isolated context (ie. isolated service worker and local storage per origin).

In my opinion this is developers custom variable that should be set in `.env.development.local` file, not in package script.

However if you really insist on setting port in package script, the cross-os way is to use [cross-env](https://www.npmjs.com/package/cross-env):

```sh
yarn add --dev cross-env
```

```diff
-   "start": "PORT=3001 react-scripts start",
+   "start": "cross-env PORT=3001 react-scripts start",
```

**Comment by qLb** [comment]
I understand and You are absolutely right this should be dealt with using cross-env. 
Let me call someone from react department so they can fix it right in the downstream. 
@thecodersio @TomaszMolenda - could we resolve this in the upcoming release (next week)?

**Comment by thecodersio** [comment]
We will do our best to include this issue in the upcoming release.

**Comment by thecodersio** [comment]
@piotr-cz Could you please send us the [disclaimer](https://github.com/ProteGO-Safe/web/tree/master/.github/PULL_REQUEST_TEMPLATE#disclaimer)  ?

**Comment by piotr-cz** [comment]
yes, I'll do so by the end of this week

**Comment by piotr-cz** [comment]
disclaimer sent
