### ISSUE TITLE
Wybór płci i forma gramatyczna

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/web#3]
Skoro aplikacja pyta o płeć Kobieta / Mężczyzna, to powinna stosować odpowiednią formę gramatyczną. 

Tymczasem w Kim jesteś wybrałam Kobieta, w następnym pytaniu:

> Czy cierpisz na jakąś dolegliwość?
> Nie, jestem **zdrowy** i nie cierpię na przewlekłe choroby
> Tak, jestem przewlekle **chory**
> Zaznacz dolegliwość, na którą cierpisz:
>nadciśnienie tętnicze
> przewlekłe choroby układu oddechowego
> choroby układu krążenia - choroba niedokrwienna serca [...]

Są 3 opcje:
- zastosować "chora/y",
- zastosować np. znak \xFE i za pomocą str_replace lub split().join() zmienić zależnie od płci na "a" lyb "y",
- przeredagować tak aby nie było słów określających płeć, (na prawdę się da!) np. 

> Czy cierpisz na jakąś dolegliwość?
> **Nie narzekam na zdrowie** i nie cierpię na przewlekłe choroby
> Tak,, **choruję przewlekle**: 
> Zaznacz dolegliwość, na którą cierpisz:
>nadciśnienie tętnicze
> przewlekłe choroby układu oddechowego
> choroby układu krążenia - choroba niedokrwienna serca [...]

---

Przepraszam za zasmarkaną sto jedenastą chusteczkę 😸 

BTW. zmieńcie wszędzie "koronawirusem"  na "koronawirusem SARS-CoV-2". 229E oraz NL63 to też koronawirusy którymi można się zarazić. 

Pytając o gorączkę - podajcie jakie jest minimum, czy polskie >38.0, czy chińskie >37.5, czy też stan podgorączkowy >37.0. Nie każdy jest medykiem a kryterium gorączki zależnie od klasyfikacji bywa różne.

**Comment by bartosztomczak** [comment]
Automatyczne dostosowanie formy gramatycznej wymagałoby przechowywania takiej informacji lokalnie w aplikacji. Wybór płci w cytowanej części aplikacji jest informacją przekazywaną na żywo do systemów diagnostycznych, które zwracają do aplikacji prawdopodobną ocenę stanu zdrowia. Proponuję stosować formy chora/y. Nie wiem tylko co na to eksperci od użyteczności stron internetowych... albo osoby korzystające z syntezatora mowy do czytania.

**Comment by SeraMoon** [comment]
Czyli niejako aplikacja zakłada możliwość zmiany płci? 

Poza tym istnieją sformułowania jak wyżej zaznaczyłam - neutralne i podałam przykład - każde zdanie da się ułożyć w ten sposób niejako stosując stronę bierną, zastępując przymiotkik rzeczownikiem itp. Hdyby był problem z którymś sformułowaniem - proszę o jego podanie (z kontekstem) to przerobię jak wyżej. 

poza tym widzę, że na części przycisków forma jest już zastosowana po wyborze płci, więc zdaje się, że gdzieś to jest pamiętane.

**Comment by SeraMoon** [comment]
Update:

> Dziennik zdrowia: 
> Miejsca i kontakty
> Z kim się **spotkałem**, gdzie **byłem**
> Metryka
> **Płeć: Kobieta**
> Wiek: 35
> Palenie: nie
> Grupa krwi: B- [...]

Proponowana zmiana - skoro jak widać płeć jest zapamiętana:

> Dziennik zdrowia: 
> Miejsca i kontakty
> **Spotkane osoby, miejsca pobytu:**
> Metryka
> Płeć: Kobieta
> Wiek: 35
> Palenie: nie
> Grupa krwi: B **Rh**- [...]

**Comment by lukalasek** [comment]
Hej, dzień dobry,
Dobra obserwacja! - dzięki za zaproponowane rozwiązania, mamy wszystkie powyższe uwagi wynotowane, wpisuję w kolejkę i fixy na pewno pojawią się w którejś z kolejnych wersji.

**Comment by Tarvald** [comment]
@SeraMoon 
Zgłoszenie zostało przyjęte
Wewnętrzny numer zgłoszenia to: PSAFE-823

**Comment by thecodersio** [comment]
Zadanie o którym wspomniał @Tarvald zostało już wdrożone i zamknięte.

@lukalasek czy uważasz, że udało nam się osiągnąć ten cel i możemy zamknąć temat ? :thinking:
