### ISSUE TITLE
Potencjalnie zbędne pytania

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/web#4]
Przy wyborze Kobieta, Kaszel+Temperatura, 37.5-40, objawy nasilają się - zbędne potencjalnie (nie znam zamysłu) jest pytanie o krwistą wydzielinę. Niezależnie od zaznaczenia status już na etapie nasilania się objawów (a może nawet wcześniej) jest czerwony. 

Warto przemyśleć obliczanie statusu na bieżąco między kolejnymi pytaniami (ekranami), aby użytkownikowi nie zaprzątać głowy odpowiedzią na pozostałe pytania, które już są zbędne do postawienia "diagnozy" skontaktowania się z sanepidem.

**Comment by lukalasek** [comment]
Nie stawiamy diagnozy, diagnozę może postawić wyłącznie lekarz :) 
Obecny flow wynika ze ścieżki API.

**Comment by bartosztomczak** [comment]
Przytoczę argument z innego wątku. Pewne części tej aplikacji pytają w kółko o to samo. Rozumiemy że to może być irytujące. Jest to pośredni dowód na to, że aplikacja nie przechowuje zbyt wielu danych na telefonie czy w pamięci przeglądarki, a ocena ryzyka odbywa się w czasie rzeczywistym. Druga sprawa to same pytania. Nie my piszemy ankiety tylko lekarze i nie nam oceniać czy nagłe wystąpienie dodatkowego objawu zmienia wynik. Powinno to być zaadresowane wyraźnie w głównej dokumentacji projektu.

Dodatkowo mam propozycję aby powołać osobne repozytorium jako miejsce docelowe do pytań i wątpliwości natury medycznej. Tam podepniemy wiki. Tam proponuję przenieść to issue jako pierwsze. Nie mogę tego jeszcze obiecać ale staramy się o lekarza, który będzie mógł udzielać bardziej fachowych odpowiedzi @SeraMoon OK?

**Comment by SeraMoon** [comment]
Na razie to widzę, brak wzięcia pod uwagę aspektów UI/UX. Zadawanie zbędnych pytań tylko wydłuża listę kliknięć. Na informatykzakladowy.pl można poczytać sobie do czego prowadzi tak długa ankieta, gdy można ją skrócić lub chociażby spakować bardziej na ekranie. Teraz gdy nie pośredniczy w tym firma trzecia - będzie to znacznie prostsze. Obecny UX tylko zachęca do rzucenia smartfonem o ścianę.

**Comment by qLb** [comment]
Czy ten watek zostal wyczerpany?
