### ISSUE TITLE
Prosty język do komunikacji

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/web#5]
Język stosowany do komunikacji z użytkownikami powinien być dostosowany do IQ=90, w tym też dla osób małoletnich oraz po samej podstawówce. 

Do poniższej listy emulując osobę z IQ=90 oraz wykształceniem podstawowym zadam następujące pytania (te osoby zazwyczaj nie czytają ulotek leków i nie wiedzą czym są leukocyty, limfopenia itp., nie skojarzą z odpornością): 

> Zaznacz odpowiedzi, które cię dotyczą
> Zdiagnozowana przewlekła choroba płuc
> Zdiagnozowana niewydolność serca
> Trwająca choroba nowotworowa
> Choroby lub leki obniżające odporność
> Zdiagnozowana przewlekła choroba wątroby
> Zdiagnozowana niewydolność nerek
> Długoterminowy pobyt w domu opieki
> Żadne z powyższych

Które choroby są przewlekłą chorobą płuc. Czy przechorowana gruźlica ze zmianami w płucach też? Astma na tle alergicznym w okresie marca i kwietnia (brak choroby od maja do lutego)? 

Czy niewydolnośc lewej komory serca to to samo co niewydolność serca? 

Które choroby obniżają odporność? Czy tylko HIV? Czy mój lek Thiamazol obniża odporność organizmu? Co z tabletkami anty? [Może jakieś przykłady najczęściej przepisywanych warto by wymienić?]

Czy stłuszczenie wątroby jest chorobą przewlekłą? Lekarz mi mówil, że po zmianie diety w 6 miesięcy wróci do normy. Jak mam zaznaczyć? Czy cysta 5mm na wątrobie to jest coś przewlekłego? [Warto podać listę nawet kosztem długości formatki!] 

Czy niewydolność jednej nerki się kwalifikuje? [użyto liczby mnogiej]

Długoterminowy czyli jaki? Miesiąc, tydzień, 3 miesiące, rok? 

---

Przepraszam za piątą zasmarkaną chusteczkę... czuję, że pozostawiłam tu koronawirusa :wink:

**Comment by lukalasek** [comment]
Dzięki za feedback - egalitaryzm to jedno z podstawowych założeń projektu.
Zweryfikujemy przytoczone scenariusze.

**Comment by Tarvald** [comment]
@SeraMoon 
Zgłoszenie zostało przyjęte
Wewnętrzny numer zgłoszenia to: PSAFE-826

**Comment by lukalasek** [comment]
W nowym flow Testu oceny ryzyka pojawiły się tooltipy, szczegółowo tłumaczące zagadnienia.
