### ISSUE TITLE
Prośba o dodanie testów do kodu

### ISSUE THREAD

**Issue by tlakomy** [ProteGO-Safe/web#8]
Cześć!

Dzięki za pracę nad aplikacją, mam nadzieję, że dzięki niej lockdown skończy się szybciej niż później.

Przeglądając kod źródłowy jedna rzecz mnie zmartwiła - mianowicie brak testów (unit/integracyjnych/e2e). Jeżeli ta aplikacja ma (docelowo) być zainstalowana przez większość społeczeństwa posiadająca smartfony to wydaje mi się, że warto przyłożyć uwagę do porządnego otestowania kodu.

Zakładam, że aplikacja jest testowana manualnie przy większych zmianach, ale to niestety może nie wystarczyć (szczególnie przy szybkim tempie rozwoju, dodawania nowych funkcjonalności etc.).

Testujemy potencjalnie zarażonych, testujmy też nasz kod, który ma ich chronić.

**Comment by tlakomy** [comment]
Szczerze mówiąc to mogę dodać nawet jakieś smoke testy z cypress.io w wolnej chwili tylko potem trzeba byłoby to zintegrować z `gitlab-ci` (do którego nie mam dostępu, więc zakładam, że to nie jest open source).

Niemniej uważam, że testy jednostkowe/integracyjne tak czy siak powinny się pojawić

**Comment by Tarvald** [comment]
@tlakomy 
Hej,
Każdy test się przyda, aczkolwiek dynamika projektu jest dość duża i testowanie czegoś co potencjalnie może zaraz zostać zmienione, może być kłopotliwe w przyszłości, proszę pamiętaj o tym. :)

 A jak będą testy to będziemy mieli możliwość wrzucić je na pipeline.

**Comment by bartosztomczak** [comment]
Zapamiętam bo to istotnie dobra uwaga. Jednak w tym konkretnym wypadku (repo web). Nie przewiduję rewolucji. Dlaczego mielibyśmy myśleć o zmianie obecnej technologii. Mamy w testach interakcyjnych czas na poziomie 0,6s dla akcji [otwórz stronę, zaczekaj aż się załaduje i kliknij button _Rozpocznij_]. Jest też pole do dalszych optymalizacji :) Mam nadzieję, że następna zmiana na produkcji zostanie już wrzucona z CI tego repozytorium. Zakładam, [że tutaj już zaglądałeś](https://github.com/ProteGO-Safe/web/blob/master/.github/workflows/nodejs.yml)?
Do pełni szczęścia brakuje tu jeszcze czyszczenia pamięci cache na poziomie Cloudflare'a bo to robimy profilaktycznie dla całej "strony" po każdej akcji deploy.

**Comment by tlakomy** [comment]
Powiem tak, wydaje mi się, że zespół ma troche inne nastawienie do testowania niż ja.

Rozumiem, że prędkość rozwijania się projektu jest szybka (i to cieszy, po co komu taka aplikacja za 5 lat), ale IMHO to nie zwalnia z pisania testów przez zespół.

Na etapie hackathonu, gdy projekt nie jest jeszcze można powiedzieć "dodamy później", ale w momencie, gdy projekt jest już:

- publiczny
- są oficjalne zalecenia, że te aplikacje (iOS/Android/Web) powinny zostać zainstalowanie przez obywateli
- pojawiają się informacje i nagłówki w mediach (nie istotne jest w tym momencie czy to jest w 100% prawda), że zainstalowanie aplikacji może być obowiązkowe dla pewnej grupy obywateli

przetestowanie kodu nie jest czymś o czym myśli się później. To jest **obowiązek**.

Po prostu martwi mnie trochę to, że klient webowy ma 0 testów, z tego co widziałem aplikacje natywne iOS/Android też, a upubliczniony backend ma ich garstkę. Rozumiem, że zespół działa w dosyć unikalnej sytuacji, ale zastanawiam się czy jesteście w stanie odpowiedzieć na pytanie:

"Czy nasza aplikacja działa w 100% zgodnie z specyfikacja?"

Bo moim prywatnym zdaniem bez testów odpowiedź na te pytanie brzmi zawsze nie.

**Comment by Tarvald** [comment]
Zgłoszenie zostało przyjęte
Wewnętrzny numer zgłoszenia to: PSAFE-824

Aczkolwiek jest, to dłuższy temat :)

**Comment by SeraMoon** [comment]
Chyba kolejne siostrzane zgłoszenie [#216](https://github.com/ProteGO-Safe/specs/issues/216)

Projekt bardzo zaniedbany.

**Comment by thecodersio** [comment]
Jeżeli chodzi o testy kodu źródłowego to staramy się je uzupełniać w raz z kolejnymi wersjami - w wersji 4.3.0 będzie można zaobserwować kolejny przyrost w tym temacie.

**Comment by TomaszMolenda** [comment]
W wersji 4.4.0 mamy 94 przypadki testowe. Wcześniej (początek projektu) faktycznie testowanie było zaniedbane - wychodzimy powoli z tego długu :muscle:
