### ISSUE TITLE
Literówka przy prośbie o wypełnienie danych zgodnie z prawdą

### ISSUE THREAD

**Issue by krskibin** [ProteGO-Safe/web#9]
**Describe the bug**
Zamiast „wypełnij” jest „pypelnij”.
![image](https://user-images.githubusercontent.com/12700136/80927554-cce30280-8d9e-11ea-8457-a207ad84f380.jpeg)

**Comment by Tarvald** [comment]
Zgłoszenie jest przyjęte. Trwają prace nad rozwiązaniem problemu.
Wewnętrzny numer zgłoszenia to: PSAFE-704

**Comment by Tarvald** [comment]
@krskibin 
Fix w 4.2 :)
